# Generated by Django 4.2.5 on 2023-10-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('locator', '0002_uniabujacampus_delete_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=252)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locator.uniabujacampus')),
            ],
        ),
    ]
